### ISSUE TITLE
Transfer to Workiva

### ISSUE THREAD

**Issue by sethladd** [Workiva/dart_to_js_script_rewriter#20]
Just added @greglittlefield-wf as a collaborator.

Head's up, we might want to help land https://github.com/sethladd/dart_to_js_script_rewriter/pull/17 before the transfer?

If transfers keep PR's, then we can transfer at any time

**Comment by sethladd** [comment]
Also, @greglittlefield-wf I'll add you as an uploader if you can give me your email address.

**Comment by greglittlefield-wf** [comment]
Looks like the PRs should remain intact after a transfer: https://help.github.com/articles/transferring-a-repository

Sure, my email is: greg.littlefield@webfilings.com

**Comment by sethladd** [comment]
Thanks. Transfer away! (I think you need to do it, as you have write permissions to both locations)

**Comment by greglittlefield-wf** [comment]
I don't see "settings" for this repository as outlined in https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts, so I think you'll have to transfer it.

Seems like the easiest way to do this will be to transfer to my account, and then I can transfer to Workiva from there.

**Comment by sethladd** [comment]
Ah, thanks for checking into that. I just initialized the transfer :)

**Comment by greglittlefield-wf** [comment]
Transfer to me complete; thanks!

We can keep this issue open until it's fully transferred to the Workiva org.

**Comment by greglittlefield-wf** [comment]
This repo is now completely transferred to Workiva. Thanks again, @sethladd!

**Comment by sethladd** [comment]
No problem, thanks for giving it a great home.

**Comment by sethladd** [comment]
Hm, it doesn't look like greg.littlefield@webfilings.com was added as an uploader. Will need to try again tonight.
