### ISSUE TITLE
Support swapping dev and deploy React scripts.

### ISSUE THREAD

**Issue by nickolaswilson-wf** [Workiva/dart_to_js_script_rewriter#41]
As a React developer,
I want a tool to automatically switch between prod and dev React scripts,
So that I can maintain error messages locally and deploy minified code seamlessly.
This seems like it'd be an apt place to put this functionality since it performs identical functionality for Dart scripts and I'm not sure many people are using Dart without React.

Acceptance criteria:
1. `<script src="packages/react/react_with_react_dom_prod.js"></script>` Used for deploys.
2. `<script src="packages/react/react.js"></script> <script src="packages/react/react_dom.js"></script>` Used for development.

**Comment by trentgrover-wf** [comment]
probably makes more sense as a separate addition to over_react - thoughts @greglittlefield-wf ?

**Comment by greglittlefield-wf** [comment]
Yeah, I'm not sure that this would belong in this repo; probably in `react-dart` if anything.

We actually have this functionality implemented internally in our web_skin_dart repo, using a simple custom transformer that evaluates `mustache` templates: https://github.com/Workiva/web_skin_dart/blob/master/lib/src/web/transformers/mustache_transformer.dart.

So, we have:
```mustache
<!-- javascript -->
{{#production}}
<script src="packages/react/react_with_react_dom_prod.js?{{ current_version }}"></script>
{{/production}}
{{^production}}
<script src="packages/react/react.js?{{ current_version }}"></script>
<script src="packages/react/react_dom.js?{{ current_version }}"></script>
{{/production}}
```
(where `production` is whether Pub is being run in `BarbackMode.RELEASE`)

Perhaps there'd be value in splitting that out.

**Comment by nickolaswilson-wf** [comment]
I'd use it :smiley:
